"""Client acceptance uses real HTTP router headers and actual generated bytes."""
import base64
import json
import subprocess
import uuid
from dataclasses import replace
from pathlib import Path
from types import SimpleNamespace

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from auth import require_auth_context
from database import database_session
from evidence_export_api import create_evidence_export_router
from test_investor_report import updated
from test_final_economics import _run
from scripts.build_evidence_export_contract import golden_run


@pytest.mark.parametrize("kind", ["full", "partial", "capacity"])
@pytest.mark.parametrize("selected", [False, True])
def test_real_backend_response_downloaded_and_adversarial_responses_rejected(kind, selected, tmp_path, monkeypatch):
    if kind == "full":
        run, linked, _ = _run(presentation_v4=True)
    elif kind == "capacity":
        run, linked = golden_run(), None
    else:
        from economics_partial import execute_partial_economics_v2
        from test_economics_partial import _context, _staffing_input
        from calculation.evidence_export import EvidenceRunSnapshotV1
        snapshot, context = _context()
        project_id = str(uuid.uuid4())
        context = replace(context, run_id=str(uuid.uuid4()), project_id=project_id,
            capacity_request=context.capacity_request.model_copy(update={"project_id": project_id}),
            capacity_response=context.capacity_response.model_copy(update={"run_id": str(uuid.uuid4())}))
        inputs = {**_staffing_input(), "calculation_depth": "BASIC", "implementation_cost_total_gross": None,
            "staffing_raas": None, "raas_monthly_per_robot_gross": None,
            "raas_contract_months": None, "raas_vendor_scope_confirmed": False}
        execution = execute_partial_economics_v2(inputs, snapshot, context)
        raw = golden_run().model_dump(mode="json")
        raw.update(run_id=context.run_id, project_id=context.project_id)
        run = updated(EvidenceRunSnapshotV1.model_validate(raw),
            inputs={"capacity_run_id": context.capacity_response.run_id, "economics": inputs},
            result=execution.result_snapshot)
        raw.update(run_id=context.capacity_response.run_id, run_kind="CAPACITY_ANALYSIS")
        linked = updated(EvidenceRunSnapshotV1.model_validate(raw),
            inputs=context.capacity_request.model_dump(mode="json"),
            result=context.capacity_response.model_dump(mode="json"))
    owner = uuid.uuid4()
    artifact = None
    query = ''
    if selected:
        from calculation.scheduling import SimulationRequestV1, run_simulation
        from calculation_contracts import semantic_digest
        from simulation_artifacts import StoredSimulationEvidence
        spec = run.scenario_spec_snapshot
        if 'profile' not in spec:
            spec = json.loads((Path(__file__).resolve().parents[1]/'contracts/fixtures/simulation-request-v1.capacity-only.golden.json').read_text(encoding='utf-8'))['scenario_spec']
            raw=run.model_dump(mode='json');raw['scenario_spec_snapshot']=spec
            raw['checksums']['scenario_spec']=semantic_digest(spec).removeprefix('sha256:')
            from calculation.evidence_export import EvidenceRunSnapshotV1
            run=EvidenceRunSnapshotV1.model_validate(raw)
        request = SimulationRequestV1.model_validate({'schema_version':'simulation-request-v1','request_id':'simulation.client.acceptance',
            'tenant_id':spec['analysis']['tenant_id'],'project_id':spec['analysis']['project_id'],'scenario_spec':spec,
            'mode':'DAILY','peak_factor':None,'sla':None,'resources':[],
            'limits':{'max_jobs_per_day':10000,'max_fleet':100,'max_runtime_seconds':60,'progress_event_batch':1000}})
        report = run_simulation(request)
        artifact = StoredSimulationEvidence(artifact_id=uuid.uuid4(),analysis_run_id=uuid.UUID(run.run_id),project_id=uuid.UUID(run.project_id),
            request=request,report=report,request_digest=semantic_digest(request),report_digest=semantic_digest(report),scenario_spec_digest=semantic_digest(request.scenario_spec))
        monkeypatch.setattr('evidence_export_api.load_artifact',lambda *args: artifact)
        query='?simulation_request_id='+request.request_id
    sources = {run.run_id: run}
    if linked:
        sources[linked.run_id] = linked
    def loader(_db, project_id, run_id, owner_id):
        return sources.get(str(run_id)) if str(project_id) == run.project_id and owner_id == owner else None
    app = FastAPI()
    app.include_router(create_evidence_export_router(loader, loader))
    app.dependency_overrides[require_auth_context] = lambda: SimpleNamespace(user=SimpleNamespace(id=owner))
    app.dependency_overrides[database_session] = lambda: SimpleNamespace(scalar=lambda *args:None)
    client = TestClient(app)
    base = f"/api/projects/{run.project_id}/analysis-runs/{run.run_id}/exports/"
    manifest = client.get(base + "manifest" + query)
    assert manifest.status_code == 200
    payload = {"manifest": manifest.json(), "projectId": run.project_id, "runId": run.run_id}
    for filename in ["investor-report.pdf", "investor-report-preview.pdf", "evidence.zip", "result.xlsx", "comparison.csv", *(["visualization.svg"] if selected else [])]:
        response = client.get(base + filename + query)
        assert response.status_code == 200
        payload[filename] = {"headers": dict(response.headers), "bytes": base64.b64encode(response.content).decode("ascii")}
    target = tmp_path / "responses.json"
    target.write_text(json.dumps(payload), encoding="utf-8")
    root = Path(__file__).resolve().parents[1]
    result = subprocess.run(["node", "--preserve-symlinks", "--preserve-symlinks-main",
        str(root / "frontend/tests/support/backend-evidence-client.mjs"), str(target)],
        cwd=root, capture_output=True, text=True, timeout=30)
    assert result.returncode == 0, result.stdout + result.stderr
