"""create catalog domain schema

Revision ID: 0002_catalog_domain
Revises: 0001_storage_control_plane
Create Date: 2026-09-16 18:30:01.412356
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0002_catalog_domain'
down_revision: Union[str, None] = '0001_storage_control_plane'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_version_id', sa.UUID(), nullable=False),
    sa.Column('source_namespace', sa.Text(), nullable=False),
    sa.Column('source_record_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('country_code', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("country_code IS NULL OR country_code ~ '^[A-Z]{2}$'", name='ck_manufacturers_country_code'),
    sa.CheckConstraint('length(btrim(name)) > 0', name='ck_manufacturers_name_nonempty'),
    sa.CheckConstraint('length(btrim(source_namespace)) > 0 AND source_namespace = btrim(source_namespace)', name='ck_manufacturers_source_namespace_nonempty'),
    sa.CheckConstraint('length(btrim(source_record_key)) > 0 AND source_record_key = btrim(source_record_key)', name='ck_manufacturers_source_record_key_nonempty'),
    sa.CheckConstraint('website_url IS NULL OR length(btrim(website_url)) > 0', name='ck_manufacturers_website_url_nonempty'),
    sa.ForeignKeyConstraint(['catalog_version_id'], ['catalog_versions.id'], name='fk_manufacturers_catalog_version_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_version_id', 'source_namespace', 'source_record_key', name='uq_manufacturers_source_key'),
    sa.UniqueConstraint('id', 'catalog_version_id', name='uq_manufacturers_id_version')
    )
    op.create_table('equipment_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_version_id', sa.UUID(), nullable=False),
    sa.Column('manufacturer_id', sa.UUID(), nullable=True),
    sa.Column('organizer_id', sa.UUID(), nullable=True),
    sa.Column('source_namespace', sa.Text(), nullable=False),
    sa.Column('source_record_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('system_family', sa.Text(), nullable=False),
    sa.Column('type_code', sa.Text(), nullable=False),
    sa.Column('subtype_code', sa.Text(), nullable=True),
    sa.Column('maturity_status', sa.Text(), nullable=True),
    sa.Column('trl', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(attributes) = 'object'", name='ck_equipment_models_attributes_object'),
    sa.CheckConstraint('length(btrim(name)) > 0', name='ck_equipment_models_name_nonempty'),
    sa.CheckConstraint('length(btrim(source_namespace)) > 0 AND source_namespace = btrim(source_namespace)', name='ck_equipment_models_source_namespace_nonempty'),
    sa.CheckConstraint('length(btrim(source_record_key)) > 0 AND source_record_key = btrim(source_record_key)', name='ck_equipment_models_source_record_key_nonempty'),
    sa.CheckConstraint('length(btrim(system_family)) > 0', name='ck_equipment_models_system_family_nonempty'),
    sa.CheckConstraint('length(btrim(type_code)) > 0', name='ck_equipment_models_type_code_nonempty'),
    sa.CheckConstraint('subtype_code IS NULL OR length(btrim(subtype_code)) > 0', name='ck_equipment_models_subtype_code_nonempty'),
    sa.CheckConstraint('trl IS NULL OR trl BETWEEN 1 AND 9', name='ck_equipment_models_trl'),
    sa.ForeignKeyConstraint(['catalog_version_id'], ['catalog_versions.id'], name='fk_equipment_models_catalog_version_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manufacturer_id', 'catalog_version_id'], ['manufacturers.id', 'manufacturers.catalog_version_id'], name='fk_equipment_models_manufacturer_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_version_id', 'organizer_id', name='uq_equipment_models_version_organizer_id'),
    sa.UniqueConstraint('catalog_version_id', 'source_namespace', 'source_record_key', name='uq_equipment_models_source_key'),
    sa.UniqueConstraint('id', 'catalog_version_id', name='uq_equipment_models_id_version')
    )
    op.create_table('catalog_source_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_version_id', sa.UUID(), nullable=False),
    sa.Column('source_artifact_id', sa.UUID(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('source_namespace', sa.Text(), nullable=False),
    sa.Column('source_record_key', sa.Text(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(raw_payload) = 'object'", name='ck_catalog_source_rows_raw_payload_object'),
    sa.CheckConstraint('length(btrim(source_namespace)) > 0 AND source_namespace = btrim(source_namespace)', name='ck_catalog_source_rows_source_namespace_nonempty'),
    sa.CheckConstraint('length(btrim(source_record_key)) > 0 AND source_record_key = btrim(source_record_key)', name='ck_catalog_source_rows_source_record_key_nonempty'),
    sa.CheckConstraint('source_row_number > 0', name='ck_catalog_source_rows_row_number_positive'),
    sa.ForeignKeyConstraint(['catalog_version_id', 'source_artifact_id'], ['catalog_version_sources.catalog_version_id', 'catalog_version_sources.source_artifact_id'], name='fk_catalog_source_rows_version_artifact', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_version_id', 'source_namespace', 'source_record_key', name='uq_catalog_source_rows_source_key'),
    sa.UniqueConstraint('id', 'catalog_version_id', name='uq_catalog_source_rows_id_version'),
    sa.UniqueConstraint('source_artifact_id', 'source_row_number', name='uq_catalog_source_rows_artifact_row')
    )
    op.create_table('equipment_applicability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_version_id', sa.UUID(), nullable=False),
    sa.Column('equipment_model_id', sa.UUID(), nullable=False),
    sa.Column('catalog_source_row_id', sa.UUID(), nullable=False),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('scenario', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('case_text', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(attributes) = 'object'", name='ck_equipment_applicability_attributes_object'),
    sa.CheckConstraint('industry IS NULL OR length(btrim(industry)) > 0', name='ck_equipment_applicability_industry_nonempty'),
    sa.CheckConstraint('region IS NULL OR length(btrim(region)) > 0', name='ck_equipment_applicability_region_nonempty'),
    sa.CheckConstraint('scenario IS NULL OR length(btrim(scenario)) > 0', name='ck_equipment_applicability_scenario_nonempty'),
    sa.ForeignKeyConstraint(['catalog_source_row_id', 'catalog_version_id'], ['catalog_source_rows.id', 'catalog_source_rows.catalog_version_id'], name='fk_equipment_applicability_source_row_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['catalog_version_id'], ['catalog_versions.id'], name='fk_equipment_applicability_catalog_version_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipment_model_id', 'catalog_version_id'], ['equipment_models.id', 'equipment_models.catalog_version_id'], name='fk_equipment_applicability_model_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_source_row_id', name='uq_equipment_applicability_source_row'),
    sa.UniqueConstraint('id', 'catalog_version_id', name='uq_equipment_applicability_id_version')
    )
    op.create_table('field_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_version_id', sa.UUID(), nullable=False),
    sa.Column('source_artifact_id', sa.UUID(), nullable=False),
    sa.Column('catalog_source_row_id', sa.UUID(), nullable=True),
    sa.Column('equipment_model_id', sa.UUID(), nullable=True),
    sa.Column('source_namespace', sa.Text(), nullable=False),
    sa.Column('source_record_key', sa.Text(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_key', sa.Text(), nullable=False),
    sa.Column('field_path', sa.Text(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_unit', sa.Text(), nullable=True),
    sa.Column('source_locator', sa.Text(), nullable=True),
    sa.Column('evidence_status', sa.Text(), nullable=False),
    sa.Column('confidence_label', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('publication_or_update_date', sa.Date(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence_label IS NULL OR confidence_label IN ('LOW', 'MEDIUM', 'HIGH')", name='ck_field_evidence_confidence_label'),
    sa.CheckConstraint("evidence_status IN ('NORMALIZED_FROM_ORGANIZER', 'ORGANIZER_CSV', 'ORGANIZER_CSV_CORROBORATING', 'ORGANIZER_ASSUMPTION', 'CORROBORATED', 'CROSS_DOCUMENT_CORROBORATING', 'CROSS_DOCUMENT_ENRICHED', 'ORGANIZER_NAME', 'VERIFIED_OFFICIAL', 'VERIFIED_AUTHORIZED_PARTNER', 'MANUALLY_APPROVED', 'CONFLICT', 'AMBIGUOUS_MODEL_MATCH', 'NOT_FOUND', 'UNKNOWN')", name='ck_field_evidence_status'),
    sa.CheckConstraint("normalized_value IS NULL OR jsonb_typeof(normalized_value) <> 'null'", name='ck_field_evidence_normalized_value_not_json_null'),
    sa.CheckConstraint("subject_type IN ('PRODUCT', 'APPLICABILITY', 'PRICE_OFFER', 'SPEC_OBSERVATION')", name='ck_field_evidence_subject_type'),
    sa.CheckConstraint('confidence_score IS NULL OR confidence_score BETWEEN 0 AND 1', name='ck_field_evidence_confidence_score'),
    sa.CheckConstraint('length(btrim(field_path)) > 0', name='ck_field_evidence_field_path_nonempty'),
    sa.CheckConstraint('length(btrim(source_namespace)) > 0 AND source_namespace = btrim(source_namespace)', name='ck_field_evidence_source_namespace_nonempty'),
    sa.CheckConstraint('length(btrim(source_record_key)) > 0 AND source_record_key = btrim(source_record_key)', name='ck_field_evidence_source_record_key_nonempty'),
    sa.CheckConstraint('length(btrim(subject_key)) > 0', name='ck_field_evidence_subject_key_nonempty'),
    sa.ForeignKeyConstraint(['catalog_source_row_id', 'catalog_version_id'], ['catalog_source_rows.id', 'catalog_source_rows.catalog_version_id'], name='fk_field_evidence_source_row_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['catalog_version_id', 'source_artifact_id'], ['catalog_version_sources.catalog_version_id', 'catalog_version_sources.source_artifact_id'], name='fk_field_evidence_version_artifact', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipment_model_id', 'catalog_version_id'], ['equipment_models.id', 'equipment_models.catalog_version_id'], name='fk_field_evidence_model_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_version_id', 'source_namespace', 'source_record_key', name='uq_field_evidence_source_key'),
    sa.UniqueConstraint('id', 'catalog_version_id', name='uq_field_evidence_id_version')
    )
    op.create_table('procurement_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_version_id', sa.UUID(), nullable=False),
    sa.Column('equipment_model_id', sa.UUID(), nullable=False),
    sa.Column('catalog_source_row_id', sa.UUID(), nullable=False),
    sa.Column('field_evidence_id', sa.UUID(), nullable=True),
    sa.Column('procurement_mode', sa.Text(), nullable=False),
    sa.Column('raw_price', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('currency_provenance', sa.Text(), nullable=True),
    sa.Column('vat_status', sa.Text(), server_default=sa.text("'UNKNOWN'"), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('vat_provenance', sa.Text(), nullable=True),
    sa.Column('price_status', sa.Text(), nullable=False),
    sa.Column('included_costs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('excluded_costs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency IS NULL OR currency ~ '^[A-Z]{3}$'", name='ck_procurement_options_currency'),
    sa.CheckConstraint("jsonb_typeof(excluded_costs) = 'array'", name='ck_procurement_options_excluded_costs_array'),
    sa.CheckConstraint("jsonb_typeof(included_costs) = 'array'", name='ck_procurement_options_included_costs_array'),
    sa.CheckConstraint("price_status IN ('RAW_UNRESOLVED', 'NORMALIZED', 'QUOTE_REQUIRED', 'UNKNOWN')", name='ck_procurement_options_price_status'),
    sa.CheckConstraint("procurement_mode IN ('PURCHASE', 'LEASE', 'RENTAL', 'RAAS', 'MANAGED_SERVICE', 'QUOTE')", name='ck_procurement_options_mode'),
    sa.CheckConstraint("vat_status <> 'ORGANIZER_ASSUMPTION_INCLUDED' OR (vat_rate IS NULL AND vat_provenance IS NOT NULL AND length(btrim(vat_provenance)) > 0)", name='ck_procurement_options_organizer_vat_assumption'),
    sa.CheckConstraint("vat_status IN ('UNKNOWN', 'ORGANIZER_ASSUMPTION_INCLUDED', 'INCLUDED', 'EXCLUDED', 'NOT_APPLICABLE')", name='ck_procurement_options_vat_status'),
    sa.CheckConstraint('amount IS NULL OR amount >= 0', name='ck_procurement_options_amount'),
    sa.CheckConstraint('currency IS NULL OR (currency_provenance IS NOT NULL AND length(btrim(currency_provenance)) > 0)', name='ck_procurement_options_currency_provenance'),
    sa.CheckConstraint('vat_rate IS NULL OR vat_rate BETWEEN 0 AND 1', name='ck_procurement_options_vat_rate'),
    sa.ForeignKeyConstraint(['catalog_source_row_id', 'catalog_version_id'], ['catalog_source_rows.id', 'catalog_source_rows.catalog_version_id'], name='fk_procurement_options_source_row_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['catalog_version_id'], ['catalog_versions.id'], name='fk_procurement_options_catalog_version_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipment_model_id', 'catalog_version_id'], ['equipment_models.id', 'equipment_models.catalog_version_id'], name='fk_procurement_options_model_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['field_evidence_id', 'catalog_version_id'], ['field_evidence.id', 'field_evidence.catalog_version_id'], name='fk_procurement_options_evidence_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_source_row_id', name='uq_procurement_options_source_row')
    )
    op.create_table('resolved_spec_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_version_id', sa.UUID(), nullable=False),
    sa.Column('equipment_model_id', sa.UUID(), nullable=False),
    sa.Column('primary_evidence_id', sa.UUID(), nullable=False),
    sa.Column('spec_code', sa.Text(), nullable=False),
    sa.Column('scope_code', sa.Text(), server_default=sa.text("'GLOBAL'"), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('json_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('canonical_unit', sa.Text(), nullable=False),
    sa.Column('resolution_status', sa.Text(), nullable=False),
    sa.Column('usable_for_matching', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('reviewed_by_subject', sa.Text(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("NOT usable_for_matching OR resolution_status IN ('CORROBORATED', 'CROSS_DOCUMENT_ENRICHED', 'ORGANIZER_NAME', 'VERIFIED_OFFICIAL', 'VERIFIED_AUTHORIZED_PARTNER', 'MANUALLY_APPROVED')", name='ck_resolved_spec_facts_matching_safe_status'),
    sa.CheckConstraint("resolution_status IN ('CORROBORATED', 'CROSS_DOCUMENT_ENRICHED', 'ORGANIZER_NAME', 'VERIFIED_OFFICIAL', 'VERIFIED_AUTHORIZED_PARTNER', 'MANUALLY_APPROVED', 'CONFLICT', 'AMBIGUOUS_MODEL_MATCH', 'NOT_FOUND', 'UNKNOWN')", name='ck_resolved_spec_facts_status'),
    sa.CheckConstraint("resolution_status NOT IN ('VERIFIED_AUTHORIZED_PARTNER', 'MANUALLY_APPROVED') OR (reviewed_by_subject IS NOT NULL AND length(btrim(reviewed_by_subject)) > 0 AND review_reason IS NOT NULL AND length(btrim(review_reason)) > 0 AND reviewed_at IS NOT NULL)", name='ck_resolved_spec_facts_review_metadata'),
    sa.CheckConstraint('length(btrim(canonical_unit)) > 0', name='ck_resolved_spec_facts_canonical_unit_nonempty'),
    sa.CheckConstraint('length(btrim(scope_code)) > 0 AND scope_code = btrim(scope_code)', name='ck_resolved_spec_facts_scope_code_nonempty'),
    sa.CheckConstraint('length(btrim(spec_code)) > 0 AND spec_code = btrim(spec_code)', name='ck_resolved_spec_facts_spec_code_nonempty'),
    sa.CheckConstraint('num_nonnulls(numeric_value, text_value, boolean_value, json_value) = 1', name='ck_resolved_spec_facts_exactly_one_typed_value'),
    sa.ForeignKeyConstraint(['catalog_version_id'], ['catalog_versions.id'], name='fk_resolved_spec_facts_catalog_version_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipment_model_id', 'catalog_version_id'], ['equipment_models.id', 'equipment_models.catalog_version_id'], name='fk_resolved_spec_facts_model_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['primary_evidence_id', 'catalog_version_id'], ['field_evidence.id', 'field_evidence.catalog_version_id'], name='fk_resolved_spec_facts_primary_evidence_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_version_id', 'equipment_model_id', 'spec_code', 'scope_code', name='uq_resolved_spec_facts_model_spec_scope'),
    sa.UniqueConstraint('id', 'catalog_version_id', name='uq_resolved_spec_facts_id_version')
    )
    op.create_index('ix_resolved_spec_facts_matching_lookup', 'resolved_spec_facts', ['catalog_version_id', 'spec_code', 'numeric_value'], unique=False, postgresql_where=sa.text('usable_for_matching'))
    op.create_table('spec_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_version_id', sa.UUID(), nullable=False),
    sa.Column('equipment_model_id', sa.UUID(), nullable=False),
    sa.Column('field_evidence_id', sa.UUID(), nullable=False),
    sa.Column('spec_code', sa.Text(), nullable=False),
    sa.Column('scope_code', sa.Text(), server_default=sa.text("'GLOBAL'"), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('numeric_value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('json_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('canonical_unit', sa.Text(), nullable=True),
    sa.Column('observation_status', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("observation_status IN ('NORMALIZED_FROM_ORGANIZER', 'ORGANIZER_CSV', 'ORGANIZER_CSV_CORROBORATING', 'ORGANIZER_ASSUMPTION', 'CORROBORATED', 'CROSS_DOCUMENT_CORROBORATING', 'CROSS_DOCUMENT_ENRICHED', 'ORGANIZER_NAME', 'VERIFIED_OFFICIAL', 'VERIFIED_AUTHORIZED_PARTNER', 'MANUALLY_APPROVED', 'CONFLICT', 'AMBIGUOUS_MODEL_MATCH', 'NOT_FOUND', 'UNKNOWN')", name='ck_spec_observations_status'),
    sa.CheckConstraint('length(btrim(scope_code)) > 0 AND scope_code = btrim(scope_code)', name='ck_spec_observations_scope_code_nonempty'),
    sa.CheckConstraint('length(btrim(spec_code)) > 0 AND spec_code = btrim(spec_code)', name='ck_spec_observations_spec_code_nonempty'),
    sa.CheckConstraint('num_nonnulls(numeric_value, text_value, boolean_value, json_value) <= 1', name='ck_spec_observations_at_most_one_typed_value'),
    sa.CheckConstraint("observation_status IN ('NOT_FOUND', 'UNKNOWN') OR num_nonnulls(numeric_value, text_value, boolean_value, json_value) = 1", name='ck_spec_observations_value_required'),
    sa.CheckConstraint("numeric_value IS NULL OR (canonical_unit IS NOT NULL AND length(btrim(canonical_unit)) > 0)", name='ck_spec_observations_numeric_unit'),
    sa.ForeignKeyConstraint(['catalog_version_id'], ['catalog_versions.id'], name='fk_spec_observations_catalog_version_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipment_model_id', 'catalog_version_id'], ['equipment_models.id', 'equipment_models.catalog_version_id'], name='fk_spec_observations_model_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['field_evidence_id', 'catalog_version_id'], ['field_evidence.id', 'field_evidence.catalog_version_id'], name='fk_spec_observations_evidence_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_spec_observations_model_spec', 'spec_observations', ['catalog_version_id', 'equipment_model_id', 'spec_code'], unique=False)
    op.create_table('resolved_spec_fact_evidence',
    sa.Column('resolved_spec_fact_id', sa.UUID(), nullable=False),
    sa.Column('field_evidence_id', sa.UUID(), nullable=False),
    sa.Column('catalog_version_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['field_evidence_id', 'catalog_version_id'], ['field_evidence.id', 'field_evidence.catalog_version_id'], name='fk_resolved_fact_evidence_evidence_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_spec_fact_id', 'catalog_version_id'], ['resolved_spec_facts.id', 'resolved_spec_facts.catalog_version_id'], name='fk_resolved_fact_evidence_fact_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('resolved_spec_fact_id', 'field_evidence_id', name='pk_resolved_spec_fact_evidence')
    )
    op.execute(
        """
        CREATE VIEW matching_spec_facts AS
        SELECT
            id,
            catalog_version_id,
            equipment_model_id,
            spec_code,
            scope_code,
            numeric_value,
            text_value,
            boolean_value,
            json_value,
            canonical_unit,
            resolution_status,
            primary_evidence_id,
            resolved_at
        FROM resolved_spec_facts
        WHERE usable_for_matching
        """
    )
    op.execute(
        """
        CREATE FUNCTION enforce_catalog_domain_draft()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            version_id uuid;
            version_status text;
        BEGIN
            IF TG_OP = 'UPDATE'
               AND NEW.catalog_version_id IS DISTINCT FROM OLD.catalog_version_id THEN
                RAISE EXCEPTION 'catalog domain rows cannot move between versions'
                    USING ERRCODE = '23514',
                          CONSTRAINT = 'ck_catalog_domain_version_immutable';
            END IF;

            IF TG_OP = 'DELETE' THEN
                version_id := OLD.catalog_version_id;
            ELSE
                version_id := NEW.catalog_version_id;
            END IF;

            SELECT status INTO version_status
            FROM catalog_versions
            WHERE id = version_id
            FOR UPDATE;

            IF version_status IS DISTINCT FROM 'DRAFT' THEN
                RAISE EXCEPTION 'catalog domain rows may change only in a DRAFT version'
                    USING ERRCODE = '23514',
                          CONSTRAINT = 'ck_catalog_domain_draft_only';
            END IF;

            IF TG_OP = 'DELETE' THEN
                RETURN OLD;
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    for table_name in (
        'manufacturers',
        'catalog_source_rows',
        'equipment_models',
        'equipment_applicability',
        'field_evidence',
        'spec_observations',
        'resolved_spec_facts',
        'resolved_spec_fact_evidence',
        'procurement_options',
    ):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table_name}_draft_only
            BEFORE INSERT OR UPDATE OR DELETE ON {table_name}
            FOR EACH ROW
            EXECUTE FUNCTION enforce_catalog_domain_draft()
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in (
        'procurement_options',
        'resolved_spec_fact_evidence',
        'resolved_spec_facts',
        'spec_observations',
        'field_evidence',
        'equipment_applicability',
        'equipment_models',
        'catalog_source_rows',
        'manufacturers',
    ):
        op.execute(f'DROP TRIGGER IF EXISTS trg_{table_name}_draft_only ON {table_name}')
    op.execute('DROP FUNCTION IF EXISTS enforce_catalog_domain_draft()')
    op.execute('DROP VIEW IF EXISTS matching_spec_facts')
    op.drop_table('resolved_spec_fact_evidence')
    op.drop_index('ix_spec_observations_model_spec', table_name='spec_observations')
    op.drop_table('spec_observations')
    op.drop_index('ix_resolved_spec_facts_matching_lookup', table_name='resolved_spec_facts', postgresql_where=sa.text('usable_for_matching'))
    op.drop_table('resolved_spec_facts')
    op.drop_table('procurement_options')
    op.drop_table('field_evidence')
    op.drop_table('equipment_applicability')
    op.drop_table('catalog_source_rows')
    op.drop_table('equipment_models')
    op.drop_table('manufacturers')
    # ### end Alembic commands ###
