"""New presentation of the immutable guest package; no engine or database writes.

The existing PDF, ZIP, manifest, inputs and simulation remain byte-for-byte intact.
Only the separately versioned investor presentation is generated by this script.
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from calculation.investor_report import Deck, GREEN, BLUE, MUTED, VERSION, amount, decimal
from calculation.readable_report import _number
from presentation import field as field_label

SOURCE = ROOT / "frontend/public/demo/warehouse-pallet-v2"
TARGET = ROOT / "frontend/public/demo/warehouse-pallet-investor-v1"
PAGE_PACKAGE = ROOT / "frontend/src/warehouseGuestPackageV2.json"


def sha(data: bytes) -> str:
    return "sha256:" + hashlib.sha256(data).hexdigest()


def load_verified_package() -> tuple[dict, str]:
    manifest_bytes = (SOURCE / "manifest.json").read_bytes()
    manifest = json.loads(manifest_bytes)
    with zipfile.ZipFile(io.BytesIO((SOURCE / "evidence.zip").read_bytes())) as archive:
        if archive.read("manifest.json") != manifest_bytes:
            raise ValueError("guest archive manifest mismatch")
        for name, meta in manifest["files"].items():
            content = archive.read(name)
            if sha(content) != meta["sha256"] or len(content) != meta["bytes"]:
                raise ValueError(f"guest archive integrity mismatch: {name}")
        payload = archive.read("package.json")
        if payload != PAGE_PACKAGE.read_bytes() or archive.read("report.pdf") != (SOURCE / "report.pdf").read_bytes():
            raise ValueError("guest page/download source mismatch")
    package = json.loads(payload)
    if package["schema_version"] != "warehouse-pallet-demo-v2" or package["bindings"] != manifest["bindings"]:
        raise ValueError("unsupported guest source or bindings")
    return package, sha(payload)


def report_bytes(package: dict) -> bytes:
    demo = package["demo"]
    scenarios = demo["scenarios"]
    if len(scenarios) != 6:
        raise ValueError("six saved commercial variants are required")
    purchase = next(s for s in scenarios if s["acquisition"] == "PURCHASE" and s["uncertainty"] == "BASE")
    raas = next(s for s in scenarios if s["acquisition"] == "RAAS" and s["uncertainty"] == "BASE")
    deck = Deck("Полный · авторский пример", package["as_of"])
    deck.page("Роботизация: сценарии и экономика", package["title"] + " · публичный проверочный пример")
    deck.card(40, 137, "Расчётный парк", f"{demo['capacity']['value']['selected_fleet']} роботов", "Перевозка подготовленных паллет")
    deck.card(234, 137, "Требуемый объём", "2 000 паллет/сутки", "2 × 11 часов; плечо 120 м")
    deck.card(428, 137, "NPV покупки", amount(purchase["npv_project"]["value"], millions=True), "Денежный контур прямого процесса", GREEN)
    deck.card(622, 137, "NPV аренды", amount(raas["npv_project"]["value"], millions=True), "Денежный контур прямого процесса", BLUE)
    deck.paragraph("Показаны сохранённые результаты полного авторского примера: покупка, аренда, шесть вариантов и чувствительность. Денежный контур прямого процесса может включать оценку дефицита персонала; это не полный проектный бюджет.", 40, 285, size=13)
    deck.paragraph("Это не подтверждённый проект и не цены организаторов. Для инвестиционного решения создайте пользовательский расчёт с проектными показателями, подтвердите объект, производительность и коммерческое предложение.", 40, 385, size=12, color=MUTED)

    deck.page("Как работает сценарий", "Один процесс и одна зона. Складская цепочка целиком не роботизирована.")
    for i, (title, text) in enumerate([("Подготовка", "Паллеты готовы к перевозке"), ("Перевозка", "Роботы выполняют рейсы"), ("Передача", "Обмен груза: 90 секунд")]):
        deck.card(40 + i * 265, 145, title, text, "Условная схема работы", GREEN if i == 1 else BLUE, width=232)
    deck.table(["Операция", "Что оценено"], [[s["operation"], "Производительность и экономика" if s["status"] == "MODELED" else "Вне расчёта денежного эффекта"] for s in package["chain"]], y=295, widths=[400, 362])

    deck.page("Шесть вариантов: диапазон результата", "NPV прямого процесса — дисконтированный эффект относительно работы без роботов, млн ₽.")
    labels = {"PURCHASE": "Покупка", "RAAS": "Аренда", "BASE": "базовый", "PESSIMISTIC": "пессимистичный", "OPTIMISTIC": "оптимистичный"}
    rows = [(labels[s["acquisition"]] + " · " + labels[s["uncertainty"]], decimal(s["npv_project"]["value"]), GREEN if s["acquisition"] == "PURCHASE" else BLUE) for s in scenarios]
    deck.bars(rows, 40, 139, 762, 270)
    deck.paragraph("Базовый профиль варианта отличается от базового уровня глубины отчёта. Профили задают условия, а не вероятность исхода. Окупаемость и подробный CAPEX не сохранены в публичном пакете и здесь не выведены из NPV.", 40, 444, size=11, color=MUTED)

    deck.page("Как меняется годовой денежный эффект", "Разность потоков против работы без роботов. Первоначальные вложения в этот график не включены.")
    deck.lines([(label, [(row["year"], decimal(row["differential_cf"])) for row in scenario["annual_ledgers"]], color) for label, scenario, color in [("Покупка", purchase, GREEN), ("Аренда", raas, BLUE)]])
    deck.text("Покупка", 70, 378, 10, GREEN)
    deck.text("Аренда", 190, 378, 10, BLUE)
    for i, (label, scenario, color) in enumerate([("Покупка", purchase, GREEN), ("Аренда", raas, BLUE)]):
        deck.card(40 + i * 390, 412, label + ": эффект первого года", amount(scenario["annual_ledgers"][0]["differential_cf"], millions=True), "Сохранённый базовый профиль", color, width=372)

    deck.page("Денежные потоки по годам", "Прямой процесс, млн ₽. Расходы — отрицательные потоки, эффект — разность с базой.")
    if [r["year"] for r in purchase["annual_ledgers"]] != [r["year"] for r in raas["annual_ledgers"]]:
        raise ValueError("guest annual windows mismatch")
    deck.table(["Год", "Без роботов", "Покупка", "Аренда", "Эффект покупки", "Эффект аренды"], [[str(p["year"]), amount(p["primary_cf_base"], millions=True), amount(p["primary_cf_scenario"], millions=True), amount(r["primary_cf_scenario"], millions=True), amount(p["differential_cf"], millions=True), amount(r["differential_cf"], millions=True)] for p, r in zip(purchase["annual_ledgers"], raas["annual_ledgers"])], widths=[45, 143, 143, 143, 144, 144], size=9)

    deck.page("Чувствительность результата", "Изменение NPV при изменении одного условия на ±10%. Значения из сохранённого проверочного расчёта.")
    variants = demo["sensitivity"]
    deck.bars([(field_label(v["override"]["parameter_id"])[0] + (" −10%" if v["override"]["direction"] == "LOWER" else " +10%"), decimal(v["npv_project"].get("delta_value")) if v["status"] != "BLOCKED" else None, GREEN) for v in variants], 40, 139, 762, 280)
    deck.paragraph("Показана сохранённая чувствительность публичного примера, а не отдельная матрица для каждого из шести вариантов. Отсутствующие значения не заменены нулями; интерактивное изменение параметров в PDF недоступно.", 40, 448, size=11, color=MUTED)

    deck.page("Сохранённая симуляция: выполнение объёма", "Модель движения и очереди; фактическая геометрия и телеметрия не предоставлены.")
    queue = package["simulation"]["report"]["queue"]
    deck.card(40, 145, "Задач в измеряемом окне", str(queue["measurement_jobs"]), "Тот же объём и парк", BLUE, width=372)
    deck.card(430, 145, "Завершено до конца окна", str(queue["completed_by_measurement_end"]), "Из сохранённой симуляции", GREEN, width=372)
    deck.paragraph("Максимальная очередь: " + str(queue["maximum_jobs"]) + " заданий. Результат не подтверждает санитарную, эксплуатационную пригодность или готовность к внедрению.", 40, 300, size=13)

    deck.page("Перед инвестиционным решением", "Границы публичного примера и проверки на объекте.")
    y = 140
    for limit in package["limitations"]:
        y = deck.paragraph("• " + limit, 40, y, size=12) + 17
    deck.paragraph("Обследование → коммерческая проверка → пилот → решение о масштабе. Полная точность исходного примера доступна в прежнем техническом ZIP; этот PDF — отдельное новое представление тех же чисел.", 40, y + 18, size=11, color=MUTED)

    assumptions = package["assumptions"]
    rows = [[field_label(k)[0], _number(v["value"]) or str(v["value"]), v["unit"], v["rationale"]] for k, v in assumptions["fields"].items()]
    for offset in range(0, len(rows), 6):
        deck.page("Приложение: авторские допущения", "Условия проверочного сценария от " + package["as_of"] + ". Не цены и не нормативы организаторов.")
        deck.table(["Условие", "Значение", "Единица", "Основание"], rows[offset:offset + 6], widths=[240, 90, 115, 317], size=9)
    deck.page("Приложение: условия и источник расчёта", "Экспорт не пересчитывает формулы, ставки, парк или симуляцию.")
    deck.table(["Условие", "Сохранённое значение"], [[field_label(k)[0], str(v)] for k, v in assumptions["other_inputs"].items()], widths=[380, 382], size=9)
    deck.page("Приложение: проверяемость", "Исторический пакет сохранён. Новая версия меняет только представление.")
    y = deck.paragraph("Источник: авторский offline-пакет " + package["schema_version"] + "; дата " + package["as_of"] + ". Глубина представления: полный авторский пример. Он создан до появления поля глубины в пользовательских расчётах; историческому снимку новая глубина не присваивалась.", 40, 139, size=11)
    for label, key in [("Результат экономики", "economics_result_digest"), ("Вход расчёта", "capacity_economics_input_digest"), ("Отчёт симуляции", "simulation_report_digest")]:
        y = deck.paragraph(label + ": " + package["bindings"][key], 40, y + 18, size=9, color=MUTED)
    deck.paragraph("Версия оформления: " + VERSION + ". Новое представление: warehouse-pallet-investor-v1. Прежний ZIP содержит исходные данные, полные значения и прежний PDF.", 40, y + 30, size=11)
    return deck.finish()


def expected_files() -> dict[Path, bytes]:
    package, source_digest = load_verified_package()
    pdf = report_bytes(package)
    manifest = {"schema_version": "guest-investor-presentation-v1", "presentation_version": VERSION,
                "depth": "FULL_AUTHORED_EXAMPLE", "source_package_digest": source_digest,
                "bindings": package["bindings"], "files": {"report.pdf": {"sha256": sha(pdf), "bytes": len(pdf)}}}
    return {TARGET / "report.pdf": pdf, TARGET / "manifest.json": (json.dumps(manifest, ensure_ascii=False, sort_keys=True, indent=2) + "\n").encode("utf-8")}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    files = expected_files()
    if args.check:
        return int(any(not p.is_file() or p.read_bytes() != body for p, body in files.items()))
    TARGET.mkdir(parents=True, exist_ok=True)
    for path, body in files.items():
        path.write_bytes(body)
        print(f"{path.relative_to(ROOT)}: {len(body)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
